Amsterdam/mijn-amsterdam-frontend

Dockerfile, Jenkinsfile
=> Eanble app building + test stages

src/App.constants.js, src/assets/icons/Chevron-Right__primary-white.svg, src/components/ButtonLink/ButtonLink.js, src/components/ButtonLink/ButtonLink.module.scss, src/components/MainFooter/MainFooter.constants.js, src/components/MainFooter/MainFooter.js, src/components/MainFooter/MainFooter.module.scss
=> [MIJN-311] Footer initial

.gitignore, mock-api/auth/check.js, mock-api/auth/index.js, mock-api/auth/state.js, package-lock.json, package.json, src/App.constants.js
=> Fix login flow mock api

Dockerfile, src/components/MainNavBar/MainNavBar.test.js, src/hooks/session.api.hook.js, src/pages/Landing/Landing.test.js
=> Add app state to tests

src/components/MijnUpdates/MijnUpdates.js
=> [MIJN-138] Fix arg

src/AppState.js, src/components/DirectLinks/DirectLinks.js, src/components/DirectLinks/DirectLinks.module.scss, src/components/Heading/Heading.js, src/components/Heading/Heading.module.scss, src/components/Heading/Heading.test.js, src/components/InfoPanel/InfoPanel.js, src/components/InfoPanel/InfoPanel.module.scss, src/components/MainHeader/MainHeader.js, src/components/MainHeader/MainHeader.module.scss, src/components/MainNavSubmenu/MainNavSubmenu.module.scss, src/components/MijnUpdates/MijnUpdates.js, src/components/MijnUpdates/MijnUpdates.module.scss, src/components/MyChaptersPanel/MyChaptersPanel.js, src/components/MyChaptersPanel/MyChaptersPanel.module.scss, src/components/PageContentMainHeading/PageContentMainHeading.js, src/components/PageContentMainHeading/PageContentMainHeading.module.scss, src/hooks/api.hook.js, src/hooks/mijn-updates-api.hook.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/Dashboard.module.scss, src/pages/MijnUpdates/MijnUpdates.js, src/pages/MijnUpdates/MijnUpdates.module.scss, src/pages/Profile/Profile.module.scss, src/styles/main.scss, src/styles/mixins/mixins.scss
@BennievanderWel hierbij in elk geval een heading component!
=> Heading component and select mixin

src/components/MainNavBar/MainNavBar.js
=> [MIJN-433] Fix chrome onFocus firing onClick

Jenkinsfile
=> Add conditions for test server

src/components/MainNavSubmenu/MainNavSubmenu.tsx
=> Nicer submenu interaction

src/components/ButtonLink/ButtonLink.module.scss, src/components/MainNavBar/MainNavBar.constants.ts, src/components/MyUpdates/MyUpdates.tsx, src/components/StatusLine/StatusLine.module.scss, src/components/StatusLine/StatusLine.tsx, src/data-formatting/focus.ts, src/data-formatting/wmo.ts, src/pages/Dashboard/Dashboard.tsx, src/pages/Inkomen/Inkomen.module.scss, src/pages/Landing/Landing.tsx, src/pages/Zorg/Zorg.module.scss, src/pages/Zorg/Zorg.tsx
=> Lastminute fixes

src/App.constants.ts, src/assets/icons/Menu.svg, src/components/ButtonLink/ButtonLink.module.scss, src/components/MainHeader/MainHeader.module.scss, src/components/MainHeader/MainHeader.test.tsx, src/components/MainHeader/MainHeader.tsx, src/components/MainNavBar/MainNavBar.constants.ts, src/components/MainNavBar/MainNavBar.module.scss, src/components/MainNavBar/MainNavBar.tsx, src/components/MainNavSubmenu/MainNavSubmenu.module.scss, src/styles/mixins/mixins.scss, src/styles/variables/_breakpoints.scss, src/styles/variables/_layout.scss
This reverts commit 2a8212c5fe78b2136f773882c8ad015e177567d6.
=> Revert "Mijn 283 alles responsive (#62)"

src/components/ErrorMessages/ErrorMessages.tsx, src/components/Modal/Modal.module.scss, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx, src/styles/_z-index.scss, src/styles/main.scss
=> [MIJN-686] Modal update

.env
=> Change api port to :5000

src/components/AutoLogoutDialog/AutoLogoutDialog.tsx
=> Format time display

.env, .env.acceptance, .env.production, package-lock.json, package.json, src/index.tsx
=> [MIJN-997] Add Sentry to front-end

src/index.tsx
=> Disable Sentry for development

src/data-formatting/brp.ts
=> Safety check

conf/nginx-server-default.template.conf
=> [MIJN-614] Whitelist api.data

Jenkinsfile, src/App.constants.ts, src/components/DirectLinks/DirectLinks.constants.ts, src/components/ErrorMessages/ErrorMessages.tsx, src/components/InfoPanel/InfoPanel.tsx, src/components/MyArea/MyArea.tsx, src/data-formatting/brp.ts, src/helpers/App.ts, src/pages/Landing/Landing.module.scss, src/pages/ZorgDetail/ZorgDetail.module.scss
=> [MIJN-709] PROD - Fixes

Jenkinsfile
=> Change Jenkins file

Jenkinsfile
=> Based on older Jenkins file

conf/nginx-server-default.template.conf
=> Add acc.data to the csp header control directive

src/components/AutoLogoutDialog/AutoLogoutDialog.module.scss, src/components/AutoLogoutDialog/AutoLogoutDialog.test.tsx, src/components/AutoLogoutDialog/AutoLogoutDialog.tsx
=> Add session timer

src/components/AutoLogoutDialog/AutoLogoutDialog.module.scss, src/components/AutoLogoutDialog/AutoLogoutDialog.test.tsx, src/components/AutoLogoutDialog/AutoLogoutDialog.tsx
=> Remove temp timer

.env.acceptance, .env.production, src/data-formatting/focus.ts, src/hooks/api/api.mymap.ts, src/styles/mixins/mixins.scss
=> [Mijn-1037] - Properly fix latest step assignment

.env, .env.acceptance, .env.production, src/hooks/analytics.hook.ts
=> Fix site id’s

.env
We should use the same version in all of our environments
=> MIJN-1071 Added the prod embed map also to the dev env

.env.production
=> New production instance

public/robots.txt, src/components/AutoLogoutDialog/AutoLogoutDialog.tsx
=> Add robots, redirect to root

src/components/StatusLine/StatusLine.module.scss, src/components/StatusLine/StatusLine.tsx, src/pages/Zorg/Zorg.tsx, src/pages/ZorgDetail/ZorgDetail.module.scss, src/pages/ZorgDetail/ZorgDetail.tsx
=> Alt document content conditional, change label

src/App.constants.ts, src/AppState.tsx, src/components/MainNavBar/MainNavBar.tsx, src/components/MyTips/MyTips.test.tsx, src/hooks/api/api.focus.ts, src/hooks/api/api.hook.ts, src/hooks/api/api.types.ts, src/hooks/api/api.wmo.ts, src/hooks/api/brp-api.hook.ts, src/hooks/api/my-tips-api.hook.ts, src/hooks/api/paginated-api.hook.test.ts, src/hooks/api/paginated-api.hook.ts, src/pages/Profile/Profile.tsx
=> [mijn-1245] Refactor api, add test, send data to tips

src/components/AutoLogoutDialog/AutoLogoutDialog.tsx
=> Explicit logout

src/pages/ZorgDetail/ZorgDetail.tsx
=> Add conditon

src/components/MyChaptersPanel/MyChaptersPanel.tsx, src/pages/Landing/Landing.tsx
=> Change case

src/components/Tutorial/Tutorial.tsx
=> Restore height

src/components/AutoLogoutDialog/AutoLogoutDialog.tsx, src/components/MainNavBar/MainNavBar.tsx
=> Remove dialog tracking, change category name

Dockerfile, Jenkinsfile
=> [mijn-1291] Enrich with more info

Dockerfile
=> [mijn-1291] Change timezone, move build-arg

Dockerfile
=> [mijn-1291] Fix timezone

readme.md, scripts/release.sh
=> Update release script

Jenkinsfile
=> Change tag setup

src/data-formatting/wmo.tsx
=> Remove date

src/pages/Dashboard/Dashboard.tsx
=> Fix loading state

src/pages/Landing/Landing.tsx
=> Text change

mock-api/json/mijn-tips.json, src/components/MyTips/MyTips.module.scss, src/components/MyTips/MyTips.tsx
=> Update tips mock + design

mock-api/auth/check.js, mock-api/auth/state.js, src/App.tsx, src/components/AutoLogoutDialog/AutoLogoutDialog.tsx, src/hooks/api/session.api.hook.ts
=> Calculate session timeout based on timestamp from api

src/components/AutoLogoutDialog/AutoLogoutDialog.test.tsx
=> Update test scenario

src/components/StatusLine/__snapshots__/StatusLine.test.tsx.snap, src/data-formatting/__snapshots__/wmo.test.ts.snap, src/data-formatting/wmo.tsx
=> [mijn-1385] Add conditional text

src/components/MyTips/MyTips.tsx
=> Image loader

Dockerfile
=> Move build env

src/helpers/App.ts
=> Fix invalid datetime

src/App.constants.ts, src/AppState.tsx, src/components/MainHeader/MainHeader.tsx, src/helpers/App.ts, src/hooks/api/api.erfpacht.ts, src/hooks/api/api.focus.ts, src/hooks/api/api.mymap.ts, src/hooks/api/api.wmo.ts, src/hooks/api/brp-api.hook.ts, src/hooks/api/my-tips-api.hook.ts, src/hooks/api/session.api.hook.ts, src/react-app-env.d.ts
=> Refactor api settings + urls usage

src/hooks/storage.hook.ts
=> Fix localstorage error in IE11 ( 8000000b)

src/styles/fonts.scss
=> Change font-weight set-up

src/hooks/storage.hook.ts
=> More try/catch

src/pages/Landing/Landing.tsx
=> [mijn-1455] Be gone with these

mock-api/brp/index.js, src/pages/Profile/Profile.test.tsx, src/pages/Profile/Profile.tsx
=> Fix bug, refactor tests

src/hooks/api/my-notifications-api.hook.ts
=> Variable welcome date

src/data-formatting/wmo.tsx
=> Remove 2 obsolete conditions

mock-api/json/focus.json, src/data-formatting/focus.test.ts, src/data-formatting/focus.tsx
=> Normalize decision type

src/data-formatting/focus.tsx
=> Remove sentry logging

src/App.constants.ts, src/pages/MyTips/MyTips.tsx
=> Enable feature toggle, typo

src/App.constants.ts, src/components/Tutorial/Tutorial.test.tsx, src/components/Tutorial/Tutorial.tsx, src/hooks/api/my-notifications-api.hook.ts
=> Welcome date and phone resizing

src/App.tsx
=> Disable usabilla for acc

src/components/Modal/Modal.tsx
=> Small aria adjustment

src/hooks/storage.hook.ts
=> Add direct reference to storage engine

src/components/Tutorial/Tutorial.module.scss, src/components/Tutorial/Tutorial.tsx, src/pages/Dashboard/Dashboard.tsx
=> Resizing tips on mobile

src/components/MainNavSubmenu/MainNavSubmenu.tsx
=> Open links in new window

src/components/MainNavBar/MainNavBar.tsx, src/components/MainNavSubmenu/MainNavSubmenu.tsx, src/components/MyChaptersPanel/MyChaptersPanel.module.scss, src/components/MyChaptersPanel/MyChaptersPanel.tsx, src/hooks/api/myChapters.hook.ts, src/hooks/api/session.api.hook.ts, src/hooks/storage.hook.ts
=> Logout try

src/components/MainNavBar/MainNavBar.tsx, src/hooks/api/session.api.hook.ts
=> Remove code

src/App.constants.ts, src/components/SectionCollapsible/SectionCollapsible.tsx, src/components/StatusLine/StatusLine.test.tsx, src/data-formatting/wmo.test.ts, src/data-formatting/wmo.tsx, src/hooks/api/api.wmo.ts, src/hooks/api/my-notifications-api.hook.ts
=> Fix code due to failing test, remove message

src/AppState.tsx, src/hooks/api/api.garbage.ts, src/hooks/api/api.hook.ts, src/hooks/api/api.types.ts, src/hooks/api/myChapters.hook.ts
=> Add abort timeout

src/AppState.tsx, src/hooks/api/myChapters.hook.ts
=> Don’t pull Garbage info if person is not from Mokum

src/components/StatusLine/StatusLine.tsx, src/data-formatting/__snapshots__/focus.test.ts.snap, src/data-formatting/focus.tsx, src/pages/ZorgDetail/ZorgDetail.tsx
=> Add documents with localstorage flag

src/components/MyArea/MyArea.module.scss, src/components/MyArea/MyArea.tsx
=> Fix wcag aria attributes

src/hooks/api/api.garbage.ts, src/pages/GarbageInformation/GarbageInformation.tsx
=> Change data

conf/nginx-server-default.template.conf
=> Add csp header

src/components/AutoLogoutDialog/AutoLogoutDialog.tsx, src/helpers/App.ts
=> Change time display and text

.env, .env.acceptance, .env.e2e, .env.production, .env.test, src/App.constants.ts
=> Mitigate env replacement bug

src/App.constants.ts, src/data-formatting/focus.tsx
=> Add feature toggle

src/components/SectionCollapsible/SectionCollapsible.test.tsx, src/components/SectionCollapsible/SectionCollapsible.tsx, src/components/SectionCollapsible/__snapshots__/SectionCollapsible.test.tsx.snap
=> Fix bug + add test

cypress/integration/tips.spec.js, src/components/MyTips/MyTipsOptInOutModal.tsx, src/pages/MyTips/MyTips.tsx
=> Change button representation

src/components/MyTips/MyTips.tsx
=> Change load handling

src/hooks/api/api.brp.ts
=> Add backward compatibility code

src/hooks/api/my-tips-api.hook.ts, src/pages/Profile/Profile.tsx
=> Adjust tips fetching

Dockerfile.test
=> Obsolete copy command

src/components/InfoPanel/InfoPanel.module.scss, src/components/InfoPanel/InfoPanel.tsx, src/data-formatting/brp.ts, src/pages/Profile/Profile.constants.ts
=> Fix layout issues and add actionLinks

src/helpers/myChapters.ts
=> Add loading condition

src/data-formatting/brp.ts
=> Change order of fields

src/hooks/api/api.mymap.ts
=> Fix special characters

cypress/integration/garbage-page.spec.js, cypress/integration/navigate-to-chapters.spec.js, cypress/integration/profile-page.spec.js, cypress/support/helpers.js, src/components/SectionCollapsible/SectionCollapsible.tsx, src/hooks/api/my-tips-api.hook.ts, src/pages/GarbageInformation/GarbageInformation.tsx
=> Add garbage spec, fix bug

src/components/MyArea/MyArea.module.scss, src/components/MyArea/MyArea.tsx, src/hooks/storage.hook.ts, src/polyfill.ts
=> Yet another localStorage bug

src/App.constants.ts
=> Disable docs

src/pages/GarbageInformation/GarbageInformation.tsx
=> Change help sentence

src/config/App.constants.ts
=> Feature toggle

Dockerfile, public/robots.txt
=> Fix build command bug

Dockerfile
=> Change operator

src/hooks/api/api.hook.ts
=> Provide initial data to empty content response

src/AppState.tsx, src/components/MainHeader/MainHeader.tsx, src/components/MyArea/MaMap.tsx, src/components/MyArea/MaMarker.tsx, src/config/Map.constants.ts, src/helpers/geo.ts, src/helpers/myChapters.ts, src/hooks/api/api.myarea.ts, src/pages/Dashboard/Dashboard.tsx, src/pages/MyArea/MyArea.tsx
=> Fix typings

src/components/MainNavBar/MainNavBar.module.scss
=> Change loader content display (ie11 neccesity)

mock-api/focus/uitkeringspecificaties.js, mock-api/json/uitkeringspecificaties.json
=> Add fake data for bijstandgegevens

src/App.tsx, src/config/Routing.constants.ts, src/pages/InkomenSpecificaties/InkomenSpecificaties.module.scss, src/pages/InkomenSpecificaties/InkomenSpecificaties.test.tsx, src/pages/InkomenSpecificaties/InkomenSpecificaties.tsx
=> Add overview page

src/hooks/analytics.hook.ts
=> Disable tracking cookies

src/hooks/analytics.hook.ts
=> Re-enable cookies

src/hooks/api/api.milieuzone.ts, src/hooks/api/my-notifications-api.hook.ts
=> Hook Milieuzone notifications

src/config/Api.constants.ts
=> Correct URL

src/config/Api.constants.ts
=> Change url

src/config/Api.constants.ts, src/config/App.constants.ts, src/helpers/myChapters.ts
=> Change default setting

mock-api/milieuzone/index.js, src/components/ErrorMessages/ErrorMessages.module.scss, src/components/ErrorMessages/ErrorMessages.tsx
=> Move Errormessages

mock-api/brp/index.js, src/components/ErrorMessages/ErrorMessages.module.scss, src/components/MyArea/MaMarker.tsx, src/components/MyArea/MyArea.module.scss, src/hooks/api/my-notifications-api.hook.ts
=> Fix some small bugs

src/components/MainHeader/MainHeader.tsx, src/config/Api.constants.ts
=> Fix error messages

mock-api/json/belasting.json, src/components/MyNotifications/MyNotifications.tsx, src/config/App.constants.ts
=> Fix url handling

src/pages/Inkomen/Inkomen.tsx
=> Enable hasItems message

src/hooks/api/api.garbage.ts
=> Update afvalpunten informatie

src/data-formatting/focus.tsx
=> Add extra safety: truthy object check

src/components/Table/Table.tsx, src/config/Chapter.constants.ts, src/data-formatting/focus.tsx, src/hooks/api/api.brp.ts, src/pages/Burgerzaken/Burgerzaken.module.scss, src/pages/Burgerzaken/Burgerzaken.tsx, src/pages/BurgerzakenDetail/BurgerzakenDetail.tsx, src/pages/GarbageInformation/GarbageInformation.module.scss, src/pages/Inkomen/Inkomen.module.scss
=> Varios sty•lis•tic issues

src/config/App.constants.ts
=> Enable belastingen on prod

src/hooks/api/api.belasting.ts, src/hooks/api/api.milieuzone.ts
=> Fix notification formatting + feature toggle milieuzone

src/pages/Dashboard/Dashboard.tsx
=> Fix for undefined tips

src/data-formatting/wmo.tsx
=> Fix unknown api response format

src/helpers/myChapters.ts
=> Always show belastingen on response error

src/data-formatting/__snapshots__/focus.test.ts.snap, src/data-formatting/focus.tsx, src/pages/InkomenDetail/InkomenDetail.tsx
=> Update snap, add step

mock-api/json/brp.json, src/data-formatting/brp.ts, src/hooks/api/api.brp.ts
=> Add doc type

public/index.html, src/public/robots.production.txt
=> Allow indexing

src/components/MainHeader/MainHeader.tsx, src/config/Api.constants.ts, src/config/StaticData.ts, src/hooks/api/my-notifications-api.hook.ts
=> Add maintenance notification

src/client/components/InfoPanel/InfoPanel.tsx, src/client/pages/Profile/Profile.test.tsx, src/client/pages/Profile/formatData.tsx, src/server/mock-data/json/brp.json, src/server/services/__snapshots__/brp.test.ts.snap, src/universal/types/brp.ts
=> Change implementation of indicatieGeheim

src/client/components/InfoPanel/InfoPanel.tsx, src/server/app.ts, src/server/config.ts, src/server/helpers/request.test.ts, src/server/helpers/request.ts, src/server/services/__service-blueprint.ts, src/server/services/afval.ts, src/server/services/bag.ts, src/server/services/belasting.ts, src/server/services/brp.ts, src/server/services/erfpacht.ts, src/server/services/focus/focus-aanvragen.ts, src/server/services/focus/focus-combined.ts, src/server/services/milieuzone.ts, src/server/services/services-cmscontent.ts, src/server/services/state.ts, src/server/services/tips.ts, src/server/services/vergunningen.ts, src/server/services/wmo.ts
=> Refactor api config + urls

src/client/hooks/useAppState.test.ts, src/client/hooks/useAppState.ts, src/client/hooks/useSSE.test.ts, src/client/hooks/useSSE.ts, src/client/pages/Profile/formatData.tsx, src/server/services/focus/focus-tozo-content.ts, src/server/services/focus/focus-tozo-helpers.ts, src/server/services/focus/focus-tozo.ts
=> Add hook tests

src/server/services/focus/focus-tozo-helpers.ts, src/server/services/focus/focus-tozo.ts
=> Add info logging

src/client/hooks/useAppState.ts, src/server/mock-data/json/focus-aanvragen.json, src/server/mock-data/json/focus-combined.json, src/server/services/focus/focus-tozo-content.ts
=> Change titles and test data

src/client/pages/Burgerzaken/Burgerzaken.tsx, src/client/pages/GarbageInformation/GarbageInformation.tsx, src/client/pages/GeneralInfo/GeneralInfo.tsx, src/client/pages/Inkomen/Inkomen.tsx, src/client/pages/InkomenDetail/InkomenDetail.tsx, src/client/pages/InkomenDetail/InkomenDetailTozo.tsx, src/client/pages/InkomenSpecificaties/InkomenSpecificaties.tsx, src/client/pages/MyTips/MyTips.tsx, src/client/pages/Profile/Profile.tsx, src/client/pages/Vergunningen/Vergunningen.tsx, src/client/pages/Zorg/Zorg.tsx, src/server/mock-data/json/vergunningen.json, src/server/services/vergunningen.ts
=> Add meldingen + loading indicators

src/client/components/Button/Button.module.scss, src/client/components/MainFooter/MainFooter.module.scss, src/client/components/MainFooter/MainFooter.tsx, src/client/components/MainFooter/amsterdam-nl-footer-data.json, src/server/mock-data/index.ts, src/server/services/services-cmscontent.ts
=> Add sub links

src/client/App.tsx, src/client/hooks/api/useSessionApi.ts, src/client/hooks/storage.hook.ts, src/client/hooks/useDeeplink.hook.ts
=> Add Deeplink hook

src/client/components/MainNavBar/ProfileName.tsx, src/client/pages/Profile/formatDataCommercial.tsx, src/server/mock-data/json/kvk-handelsregister.json, src/server/services/kvk.ts
=> Adjust profile display according to response

src/client/components/MainNavBar/ProfileName.tsx
=> Fix tutorial items display

src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.tsx, src/client/pages/ToeristischeVerhuurDetail/ToeristischeVerhuurDetail.tsx, src/server/services/toeristische-verhuur.ts, src/universal/helpers/api.ts
Fix an error where details of a permit were not shown because a partial error in the api result occurred.
=> Fix error display + handling

src/server/mock-data/json/focus-combined.json, src/server/services/focus/__snapshots__/focus-tozo.test.ts.snap, src/server/services/focus/focus-tozo-content.ts, src/server/services/focus/focus-tozo.ts, src/server/services/focus/focus-types.ts
=> Add Tozo 5 initial document

src/server/mock-data/json/focus-combined.json, src/server/services/focus/__snapshots__/focus-tozo.test.ts.snap, src/server/services/focus/focus-tozo-content.ts
=> Add tozo 5 doc codes

src/server/mock-data/json/focus-combined.json, src/server/services/focus/__snapshots__/focus-tozo.test.ts.snap, src/server/services/focus/focus-tozo-content.ts
=> Add more codes

src/client/config/menuItems.ts, src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.tsx, src/server/mock-data/index.ts, src/server/services/controller.ts, src/server/services/generated.ts, src/server/services/toeristische-verhuur.test.ts, src/server/services/toeristische-verhuur.ts
=> Add toeristische verhuur for commercial users

src/client/components/DocumentList/DocumentList.module.scss, src/client/components/DocumentList/DocumentList.test.tsx, src/client/components/DocumentList/DocumentList.tsx, src/client/pages/BurgerzakenDetail/__snapshots__/BurgerzakenAkte.test.tsx.snap, src/client/pages/Inkomen/__snapshots__/Inkomen.test.tsx.snap, src/client/pages/InkomenSpecificaties/__snapshots__/InkomenSpecificaties.test.tsx.snap, src/client/pages/StatusDetail/StatusDetail.test.tsx, src/client/pages/StatusDetail/__snapshots__/StatusDetail.test.tsx.snap
Add spinner and disable click if a document is being downloaded.
=> Add download spinner, add external conditional

src/client/components/MyArea/MyArea.hooks.ts, src/client/hooks/api/useDataApi.ts, src/server/helpers/source-api-request.ts
Add some custom ua headers for whitelisting
=> Add UA headers

src/server/services/toeristische-verhuur.ts
=> Add In behandeling notification

src/client/pages/Inkomen/Inkomen.tsx, src/client/pages/Stadspas/Stadspas.tsx, src/client/pages/StadspasDetail/StadspasAanvraagDetail.tsx, src/server/services/focus/__snapshots__/focus-aanvragen.test.ts.snap, src/server/services/focus/__snapshots__/focus-tonk.test.ts.snap, src/server/services/focus/__snapshots__/focus-tozo.test.ts.snap, src/server/services/focus/focus-aanvragen-helpers.ts, src/server/services/focus/focus-aanvragen.test.ts, src/server/services/focus/focus-aanvragen.ts, src/server/services/focus/focus-tonk.ts, src/server/services/focus/focus-toxx-helpers.ts, src/server/services/focus/focus-tozo.ts, src/server/services/focus/focus-types.ts
- Fixes display of decision date on overview page
- Fixes unwanted grouping in lopende aanvragen
=> Mijn 3296 fat tonk

src/client/components/DocumentList/DocumentList.tsx, src/client/pages/BurgerzakenDetail/__snapshots__/BurgerzakenAkte.test.tsx.snap, src/client/pages/Inkomen/__snapshots__/Inkomen.test.tsx.snap, src/client/pages/InkomenSpecificaties/__snapshots__/InkomenSpecificaties.test.tsx.snap, src/client/pages/StatusDetail/StatusDetail.tsx, src/client/pages/StatusDetail/__snapshots__/StatusDetail.test.tsx.snap, src/server/services/focus/__snapshots__/focus-tozo.test.ts.snap, src/server/services/focus/focus-aanvragen-helpers.ts, src/server/services/focus/focus-tonk-content.ts, src/server/services/focus/focus-toxx-helpers.ts, src/server/services/focus/focus-tozo-content.ts, src/server/services/focus/focus-types.ts
=> Use different property to determine decision status

src/client/components/MainNavBar/MainNavBar.tsx, src/client/components/Search/Search.tsx, src/client/components/Search/searchConfig.tsx, src/client/components/Search/useSearch.test.tsx, src/client/hooks/analytics.hook.ts, src/universal/config/app.ts
- Add some analytics
- Prevent error in search tracking
- Add feature toggle
=> Search improvements

src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.test.tsx, src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.tsx, src/client/pages/ToeristischeVerhuur/__snapshots__/ToeristischeVerhuur.test.tsx.snap
Verwijderd code die niet meer uitgevoerd wordt.
=> MIJN-3543 - Remove unused code about disclaimers

src/client/pages/VergunningDetail/Flyeren.tsx, src/client/pages/VergunningDetail/VergunningDetail.module.scss, src/client/pages/VergunningDetail/VergunningDetail.test.tsx, src/client/pages/VergunningDetail/VergunningDetail.tsx, src/client/pages/VergunningDetail/__snapshots__/VergunningDetail.test.tsx.snap, src/client/pages/Vergunningen/__snapshots__/Vergunningen.test.tsx.snap, src/server/mock-data/json/vergunningen.json, src/server/services/vergunningen/__snapshots__/vergunningen.test.ts.snap, src/server/services/vergunningen/vergunningen.ts, src/universal/helpers/vergunningen.ts, src/universal/types/vergunningen.ts
Heeft dit PR ook nodig: https://github.com/Amsterdam/mijn-decos-join-api/pull/56/files
=> MIJN-4168 - Toevoegen flyeren vergunningen

readme.md, src/client/App.tsx
- Trying to avoid the Landing page chunk load errors
- Also use redirects for non-logged-in users. After login they will be sent to the correct page.
=> Fix sentry errors

src/universal/config/app.ts
Op verzoek PO deze PR terug gedraaid.
=> Revert "MIJN-3754 -Turn on sia meldingen"

src/server/config.ts
Try to mitigate NBF claim fails. The code suggests increasing the clockTolerance might mitigate the problem.
=> Increase clock tolerance

package-lock.json, package.json
Achterstallige tag + version update
=> MIJN-7849 - Bump! release-v4.92.0

conf/nginx-server-default.template.conf, package-lock.json, package.json, src/server/app.ts, src/server/config.ts
MIJN-8126 - Remove rate limiting (in favor of AppGW)
MIJN-8127 - Remove rate limiting (in favor of AppGW)
MIJN-8129 - Remove header config (in favor of AppGW)
=> MIJN-8125 - Security improvements

src/server/app.ts, src/server/config.ts, src/server/helpers/auth.ts, src/server/router-development.ts, src/server/router-oidc.ts, src/server/services/hli/hli-zorgned-service.ts, src/server/services/hli/router-external-consumer.ts, src/server/views/amsapp-stadspas-clientnummer.pug
=> Mijn-8893 stadspas digid clientnr api

src/server/services/vergunningen-v2/decos-service.ts, src/server/services/vergunningen-v2/vergunningen-notifications.ts, src/server/services/vergunningen-v2/vergunningen.ts, src/server/services/vergunningen/vergunningen.ts
Explicitly set argument length for correct memoization
=> Mijn-8299 fix filtering

vite.config.ts, vitest.config.ts
Add vitest config for making global visible within IDEA editors
=> chore-8971/Add vitest config

src/server/services/hli/stadspas-router-external-consumer.test.ts, src/server/services/hli/stadspas-router-external-consumer.ts
- Always render html on error at login endpoint
- Separate decrypt + fetch operations
=> [MIJN-8883-Feature] - Change error handling

mocks/fixtures/zorgned-jzd-aanvragen.json, src/client/pages/VergunningDetail/VergunningDetail-RVVSloterweg.test.tsx, src/server/services/hli/hli-zorgned-service.ts, src/server/services/wmo/__snapshots__/wmo.test.ts.snap, src/server/services/wmo/status-line-items/wmo-diensten.ts, src/server/services/wmo/status-line-items/wmo-generic.ts, src/server/services/wmo/status-line-items/wmo-hulpmiddelen.ts, src/server/services/wmo/status-line-items/wmo-wra.ts, src/server/services/wmo/wmo-zorgned-service.test.ts, src/server/services/wmo/wmo-zorgned-service.ts, src/server/services/wmo/wmo.ts, src/server/services/zorgned/__snapshots__/zorgned-service.test.ts.snap, src/server/services/zorgned/zorgned-helpers.test.ts, src/server/services/zorgned/zorgned-helpers.ts, src/universal/config/feature-toggles.ts
This is an implementation that will only possibly work with the new Doc titles available.
=> [MIJN-9058-Feature] - Determine besluit status + date

mocks/collections.json, mocks/routes/afis.js, src/client/App.tsx, src/client/config/api.ts, src/client/pages/Afis/Afis.tsx, src/server/config.ts, src/server/router-protected.ts, src/server/services/afis/afis-route-handlers.ts, src/server/services/afis/afis-types.ts, src/server/services/afis/afis.test.ts, src/server/services/afis/afis.ts, src/universal/config/thema.ts
Add afis services and tests. Remove axios error. Add FE, mockdata ids, types
**for testers**
I created mock data:  get-afis-businesspartner-details,  get-afis-businesspartner-phonenumber. 
Left some data which is not touched out. Should I add it anyways? I thought not for the sake of clarity. 
```{
"feed": {
"@base": "https://vams-asa-00.gemams.am.loc:44300/sap/opu/odata/sap/ZAPI_BUSINESS_PARTNER_DET_SRV/",
"id": "https://vams-asa-00.gemams.am.loc:44300/sap/opu/odata/sap/ZAPI_BUSINESS_PARTNER_DET_SRV/A_AddressPhoneNumber",
"title": {
"@type": "text",
"$": "A_AddressPhoneNumber"
},
"updated": "2024-08-08T10:53:38Z",
"author": {
"name": ""
},
"link": {
"@href": "A_AddressPhoneNumber",
"@rel": "self",
"@title": "A_AddressPhoneNumber"
},
"entry": [
{
"id": …
```
=> MIJN-9037/Stamdata business partner endpoint

mocks/collections.json, mocks/routes/gpass.js, src/server/config.ts, src/server/services/hli/stadspas-router-external-consumer.test.ts, src/server/services/hli/stadspas-router-external-consumer.ts
- Appended `/gelukt` or `/mislukt` (error) to deeplink
- Added header to potentially fix login bug
- Fixed wrongly named URL parameter
=> MIJN-9109-FEATURE-ams-app-wenst-iets-andere-werking-van-de-login-workflow

.github/workflows/pr-title-check.yml, .github/workflows/release-notification.yml
##Voor testers
releases:
Getest in eigen omgeving. Zie er zo uit, met linkjes naar de commits en de pull requests. De eerste chore zal niet voorbij de title check komen
=> MIJN-9003-FEATURE-workflow-pr-title-check-aanpassen

src/server/config.ts, src/server/helpers/app.ts, src/server/openapi-amsapp.yml, src/server/services/hli/hli-route-handlers.ts, src/server/services/hli/stadspas-gpass-service.ts, src/server/services/hli/stadspas-router-external-consumer.test.ts, src/server/services/hli/stadspas-router-external-consumer.ts, src/server/services/hli/stadspas-types.ts, src/server/services/hli/stadspas.test.ts, src/server/services/hli/stadspas.ts, src/test-utils.ts
- Transformatie van data
- Update van swagger def
- Andere benaming van functies
- Test updates
=> Mijn-9128-Feature refactor service a bit

src/server/openapi-amsapp.yml, src/server/services/hli/stadspas-gpass-service.ts, src/server/services/hli/stadspas-types.ts, src/server/services/hli/stadspas.test.ts
- Added two fields
- Adjusted types
Ik twijfel over de response als het undefined of leeg is dan default ik naar 0 want dan ook geen korting. Maar is dat wel een goed ontwerp? moet ik dan geen null geven?
Ziet er nu zo uit:
```
{
"content": {
"discountAmountTotal": 0,
"discountAmountTotalFormatted": "€0,00",
"transactions": []
},
"status": "OK"
}
```
=> MIJN-9137-CHORE-toevoegen-totale-korting-in-aanbiedingen-transacties-stadspas-api-voor-app-team

src/server/services/db/config.ts, src/server/services/db/db.test.ts, src/server/services/db/db.ts, src/setupTests.ts, src/universal/config/feature-toggles.ts
Mocked featuretoggles by setting them all active in `setupTests.ts`
=> MIJN-9133-CHORE-mock-feature-toggles-in-tests-alg-techniek

src/client/pages/Zorg/ZorgV2.tsx
MIJN-9187 - disclaimer, MIJN-9186 - Inleidende tekst
=> MIJN-9187-Feature-MIJN-9186-Feature - disclaimer, MIJN-9186 - Inleidende tekst

src/client/pages/GarbageInformation/GarbageInformation.test.tsx, src/client/pages/GarbageInformation/GarbageInformation.tsx, src/client/pages/GarbageInformation/__snapshots__/GarbageInformation.test.tsx.snap
=> MIJN-9155-Chore - Remove stadsdeelaanvulling

azure-pipeline-bff.yaml, azure-pipeline-ui.yaml, azure-pipelines.yaml
- alle aquasec mentions verwijderd
Deze hoort hierbij: https://dev.azure.com/CloudCompetenceCenter/MijnAmsterdam/_git/mijn-amsterdam-infra/pullrequest/35989
=> MIJN-9573-CHORE-aqua-sec-uitfaseren-voor-20-dec-alg-techniek

src/client/components/LocationModal/LocationModal.tsx, src/client/components/MyArea/MyArea.hooks.ts, src/client/pages/Bodem/__snapshots__/LoodMeting.test.tsx.snap, src/client/pages/HorecaDetail/__snapshots__/HorecaDetail.test.tsx.snap, src/client/pages/ToeristischeVerhuur/ToeristischeVerhuurDetail.test.tsx, src/client/pages/ToeristischeVerhuur/ToeristischeVerhuurDetail.tsx, src/client/pages/VergunningDetail/__snapshots__/VergunningDetail.test.tsx.snap, src/server/auth/auth-config.ts, src/server/services/toeristische-verhuur/toeristische-verhuur-notifications.ts, src/server/services/toeristische-verhuur/toeristische-verhuur-powerbrowser-bb-vergunning.test.ts, src/server/services/toeristische-verhuur/toeristische-verhuur-powerbrowser-bb-vergunning.ts, src/universal/helpers/brp.ts
- Geen default lat/lon locatie op kaart gebruiken
- Link om Locatiemodal te openen vervangen met een Design system button
- Separator optie in getFullAddress toegevoegd
- Adres in mailbody van andere separator voorzien
- Melding Meer informatie nodig aangepast
=> Mijn-9516-Feature - vergunning fat bevindingen

.env.local.template, src/testing/setup.ts
Console was spammed with env messages
=> MIJN-9809-Chore - Use env template file for default env values

src/client/pages/VergunningenV2/VergunningDetail.tsx, src/server/services/decos/decos-service.test.ts, src/server/services/decos/decos-service.ts, src/server/services/decos/decos-types.ts, src/server/services/decos/helpers.ts, src/server/services/vergunningen-v2/config-and-types.ts, src/server/services/vergunningen-v2/decos-zaken.ts, src/server/services/vergunningen-v2/vergunningen-notification-labels.ts, src/server/services/vergunningen-v2/vergunningen-notifications.ts, src/server/services/vergunningen-v2/vergunningen-status-steps.ts, src/server/services/vergunningen-v2/vergunningen.ts, src/universal/helpers/types.ts
=> MIJN-9587-CHORE Fetch multiple workflow status dates

azure-release-pipeline.yaml
See also: https://stackoverflow.com/a/63250109/756075
=> Mijn-10018-bug pipeline release trigger

src/client/components/Datalist/Datalist.module.scss, src/client/components/Datalist/Datalist.tsx, src/client/pages/Varen/Varen.tsx
Ik weet niet of de verdeling van de gegevens en de labels zo goed zijn maar het idee is duidelijk!
=> Improve grid finetuning for Datalist

mocks/collections.json, mocks/fixtures/decos-vergunningen-termijnens-response.json, mocks/routes/decos.js, src/server/services/decos/decos-service.ts, src/server/services/decos/decos-types.ts, src/server/services/varen/decos-zaken.ts, src/server/services/varen/varen-status-steps.ts, src/universal/helpers/date.ts
Wil dit het liefst voor morgen mergen ivm de ketentest dus als je er alvast naar wilt kijken?
Ik moet het volgende nog doen:
Aangezien er niet een duidelijke actiecode is om de zaak status op in behandeling te zetten begint deze standaard op in behandeling
=> MIJN-10062-FEATURE Add termijnen for varen zaken

.env.local.template, src/server/config/source-api.ts, src/server/services/afis/afis-helpers.ts
Enable-U didn't install generic api key for every api yet
=> MIJN-10012-Chore - Restore keys

src/client/pages/Bodem/Bodem.test.tsx, src/client/pages/Bodem/LoodMeting.test.tsx, src/client/pages/Bodem/LoodMeting.tsx, src/server/services/bodem/loodmeting.test.ts, src/server/services/bodem/loodmetingen.ts, src/server/services/bodem/types.ts
=> MIJN-100190-CHORE - Refactor Bodem decision toegewezen to afgehandeld and remove resultaat from detail page

src/client/components/MainFooter/MainFooter.constants.ts, src/client/pages/Thema/Bodem/Bodem-thema-config.ts, src/client/pages/Thema/Inkomen/Inkomen-thema-config.ts, src/client/pages/Thema/Jeugd/Jeugd-thema-config.ts, src/client/pages/Thema/Krefia/useKrefiaThemaData.hook.tsx, src/client/pages/Thema/ToeristischeVerhuur/useToeristischeVerhuur.hook.ts, src/server/services/content-tips/tips-content.ts, src/server/services/toeristische-verhuur/toeristische-verhuur-notifications.ts, src/server/services/toeristische-verhuur/toeristische-verhuur-powerbrowser-bb-vergunning.ts, src/server/services/wpi/content/bijstandsuitkering.ts
Op basis van excel lijst https://gemeente-amsterdam.atlassian.net/jira/software/c/projects/MIJN/boards/1237?assignee=63d7813f28cddcc7076fe259&selectedIssue=MIJN-11486 in de laatste comments
=> MIJN-11486-CHORE-niet-werkende-links-herstellen-part-excel-ilka

src/server/openapi-amsapp-notificaties.yml
=> MIJN-11724-BUG Correct endpoints to use notifications over notificaties

src/client/components/Table/TableV2.tsx, src/client/pages/Thema/AVG/useAVGData.hook.tsx, src/client/pages/Thema/Bezwaren/useBezwarenThemaData.hook.ts, src/client/pages/Thema/Bodem/useBodemData.hook.tsx, src/client/pages/Thema/Burgerzaken/useBurgerZakenData.hook.tsx, src/client/pages/Thema/Erfpacht/useErfpachtThemaData.hook.ts, src/client/pages/Thema/HLI/useHliThemaData.ts, src/client/pages/Thema/Horeca/useHorecaThemaData.hook.ts, src/client/pages/Thema/Inkomen/useInkomenThemaData.hook.ts, src/client/pages/Thema/Jeugd/useJeugdThemaData.ts, src/client/pages/Thema/Klachten/useKlachtenThemaData.hook.ts, src/client/pages/Thema/Krefia/useKrefiaThemaData.hook.tsx, src/client/pages/Thema/Parkeren/useParkerenData.hook.tsx, src/client/pages/Thema/ToeristischeVerhuur/useToeristischeVerhuur.hook.ts, src/client/pages/Thema/Varen/useVarenThemaData.hook.ts, src/client/pages/Thema/Vergunningen/useVergunningenThemaData.hook.ts, src/client/pages/Thema/Zorg/useZorgThemaData.ts
Zat even naar je tickets te kijken en zag deze, en toen schoot dit naar binnen bij me. Vraag me af wat je ervan vind, want nu kan je wel duidelijk zien wat voor Component je aan het toevoegen bent. Ik kan me voorstellen dat die misschien nog voor gaat komen.
=> Gecurriede functie gebruiken zodat we MaLink of MaRouterLink kunnen gebruiken

src/client/components/MyArea/InfoSection.tsx, src/client/hooks/useThemaMenuItems.test.tsx, src/client/hooks/useThemaMenuItems.ts, src/client/pages/GeneralInfo/GeneralInfo.tsx, src/client/pages/Thema/AVG/InfoSection.tsx, src/client/pages/Thema/Afis/InfoSection.tsx, src/client/pages/Thema/Afval/InfoSection.tsx, src/client/pages/Thema/Belastingen/InfoSection.tsx, src/client/pages/Thema/Bezwaren/InfoSection.tsx, src/client/pages/Thema/Bodem/InfoSection.tsx, src/client/pages/Thema/Burgerzaken/InfoSection.tsx, src/client/pages/Thema/Erfpacht/InfoSection.tsx, src/client/pages/Thema/HLI/InfoSection.tsx, src/client/pages/Thema/Inkomen/InfoSection.tsx, src/client/pages/Thema/Jeugd/InfoSection.tsx, src/client/pages/Thema/Klachten/InfoSection.tsx, src/client/pages/Thema/Krefia/InfoSection.tsx, src/client/pages/Thema/Milieuzone/InfoSection.tsx, src/client/pages/Thema/Overtredingen/InfoSection.tsx, src/client/pages/Thema/Parkeren/InfoSection.tsx, src/client/pages/Thema/Profile/InfoSection.tsx, src/client/pages/Thema/Profile/commercial/ProfileCommercial.transform.tsx, src/client/pages/Thema/Subsidies/InfoSection.tsx, src/client/pages/Thema/ToeristischeVerhuur/InfoSection.tsx, src/client/pages/Thema/Vergunningen/InfoSection.tsx, src/client/pages/Thema/Zorg/InfoSection.tsx
https://gemeente-amsterdam.atlassian.net/browse/MIJN-11094
=> MIJN-11094-feature-toggle-verwerken-in-uitlegpagina

src/server/routing/router-public.ts
Goed idee Tim om dit permanent mogelijk te maken
=> MIJN-12057-CHORE Allow disabling cobrowse screenshare from bff env
